'use strict';
// Kelajak elementlarini bugungi sharoitda yasash bilimlar bazasi (oflayn).
// trl: 1-9 texnologik tayyorlik darajasi (bugun). cost: 1 (arzon) .. 5 (qimmat)
const KB = [
 {id:'energy', name:'Energiya manbai', kw:['energiya','quyosh','batareya','quvvat'], trl:8, cost:2,
  today:'Litiy-ion/LiFePO4 batareya, ixcham quyosh panellari, kinetik (harakatdan) energiya yig‘ish, simsiz zaryad (Qi).',
  gap:'Haftalab/oylab zaryadlanmasdan ishlash va ko‘rinmas, yupqa energiya hali cheklangan.',
  parts:['LiPo/LiFePO4 batareya','Zaryad kontrolleri (TP4056/BQ25570)','Mini quyosh paneli','Qi simsiz zaryad moduli'],
  tools:['Multimetr','Lehim stansiyasi'], skills:['Elektronika asoslari','Batareya xavfsizligi'],
  mock:'Tashqi quvvat bloki bilan ishlaydigan "o‘ynoqi" maket.',
  poc:'Sensor va kontrollerni bitta batareyadan ishlatib, sarfni (mA) o‘lchash.',
  proto:'Energiya byudjeti hisobi, uyqu rejimi (deep sleep), korpusga joylash.'},
 {id:'display', name:'Ekran / yorug‘lik / proyeksiya', kw:['ekran','ko‘rsat','yoruq','yorug','proyeksiya','vizual','ar','hologram'], trl:8, cost:3,
  today:'OLED/e-ink ekranlar, LED matritsa, mini-proyektorlar, AR ko‘zoynaklar, volumetrik effektli ko‘zgu-ekranlar.',
  gap:'Haqiqiy havodagi gologramma yo‘q; AR ko‘zoynaklar hajmli va qimmat.',
  parts:['OLED/e-ink modul','WS2812 LED lenta','Mini proyektor/pico-projector','Telefon (AR uchun)'],
  tools:['Figma','Arduino IDE / MicroPython'], skills:['UI dizayn','Oddiy dasturlash'],
  mock:'Telefon ekranida Figma/video bilan interfeysni namoyish qilish.',
  poc:'ESP32 + kichik ekranda asosiy ma’lumotni ko‘rsatish.',
  proto:'Maxsus korpusga ekran/LED joylash, yorqinlik va qulaylikni sinash.'},
 {id:'sensors', name:'Sensorlar / sezgilar', kw:['sensor','iot','o‘lcha','kuzat','sezgi','monitor'], trl:9, cost:2,
  today:'Harorat, namlik, harakat, bosim, gaz, EKG/puls (PPG), kamera, mikrofon sensorlari juda arzon va tayyor.',
  gap:'Noinvaziv glyukoza, hid va ruhiy holat kabi murakkab o‘lchovlar hali aniq emas.',
  parts:['ESP32/Arduino','BME280, MPU6050, MAX30102 kabi modullar','Qo‘shimcha: gaz/PM2.5 sensori'],
  tools:['Breadboard','Serial plotter'], skills:['Arduino/MicroPython','Ma’lumotni tozalash'],
  mock:'Sensor o‘rniga qo‘lda kiritilgan ma’lumotlar.',
  poc:'1–2 ta sensordan real ma’lumot olib, grafikda ko‘rsatish.',
  proto:'Kalibrovka, ko‘p sensor sinxronlashi, shovqinni filtrlash.'},
 {id:'ai', name:'Sun’iy intellekt / aql', kw:['sun’iy','intellekt','ai','mashinaviy','aqlli','bashorat','shaxsiy'], trl:8, cost:2,
  today:'Katta til modellari (Claude va boshqalar) API orqali, kompyuter ko‘rishi, ovoz tanish, qurilmada ishlaydigan kichik modellar (TinyML).',
  gap:'Ishonchlilik, xatolar va maxfiylik: muhim qarorlarda inson nazorati zarur.',
  parts:['LLM API (bulut)','Raspberry Pi / telefon (qurilmada)','Mikrofon/kamera'],
  tools:['Python/JavaScript','Prompt va sinov to‘plami'], skills:['API ishlatish','Ma’lumot etikasi'],
  mock:'"Sehrgar" usuli: javobni odam qo‘lda yozadi, foydalanuvchi AI deb o‘ylaydi.',
  poc:'LLM API bilan 1 ta vazifani avtomatlashtirish va 20 ta misolda sinash.',
  proto:'Xavfsizlik filtrlari, inson tasdig‘i, xatoni qayd etish va yaxshilash sikli.'},
 {id:'motion', name:'Harakat / mexanika / robot', kw:['robot','harakat','mexanik','dron','yurish','manipulyator','ushlab'], trl:7, cost:4,
  today:'Servo va qadamli motorlar, 3D bosma mexanizmlar, arzon robot qo‘llari, dronlar, ekzoskeletlar (tijoriy, qimmat).',
  gap:'Inson kabi yengil, xavfsiz va arzon "yumshoq" robotlar hali laboratoriyada.',
  parts:['Servo/qadamli motor','Motor drayver','Metall/3D bosma ramka','Enkoder/limit sensorlar'],
  tools:['3D printer','Lehim, vint-gayka asboblari'], skills:['Mexanika','Boshqaruv dasturi'],
  mock:'Karton/ko‘pik maket va qo‘lda tortiladigan "harakat" video.',
  poc:'1 ta servoli oddiy mexanizmni ishlatish.',
  proto:'Yuk, xavfsizlik (qisish xavfi) va shovqinni hisobga olgan to‘liq mexanizm.'},
 {id:'material', name:'Material / shakl / qobiq', kw:['material','shakl','korpus','kiyil','mato','qobiq','yengil','qayta ishlangan','eko'], trl:8, cost:3,
  today:'3D bosma (PLA/PETG/TPU), qayta ishlangan plastik, biokompozitlar (mitseliy, qog‘oz-pulpa), elektr o‘tkazuvchi matolar, silikon quyish.',
  gap:'O‘z-o‘zini tiklaydigan yoki shaklini o‘zgartiruvchi "aqlli" materiallar kam va qimmat.',
  parts:['3D bosma filament','Silikon/epoksi','Mato va tikuv materiallari','O‘tkazuvchi ip'],
  tools:['3D printer (yoki mahalliy 3D xizmat)','Fusion 360 / Blender'], skills:['3D modellash','Material sinovi'],
  mock:'Karton, plastilin yoki ko‘pikdan 1:1 maket.',
  poc:'3D bosma korpus va asosiy qismlar joylashishini tekshirish.',
  proto:'Tanlangan material, rang, sirt va mustahkamlikni sinash; ekologik variant.'},
 {id:'connect', name:'Aloqa / tarmoq', kw:['aloqa','tarmoq','ulan','masofaviy','bluetooth','wifi','internet','hamkorlik'], trl:9, cost:1,
  today:'BLE, Wi-Fi, LoRa (uzoq masofa, kam quvvat), 4G/5G, mesh tarmoqlar, sun’iy yo‘ldosh aloqasi (qimmat).',
  gap:'Internetsiz hududlarda arzon va doimiy aloqa hamon qiyin.',
  parts:['ESP32 (BLE/Wi-Fi)','LoRa moduli','SIM/IoT modul'],
  tools:['Telefon ilovasi / veb-panel'], skills:['Tarmoq asoslari','Oflayn-birinchi dizayn'],
  mock:'Telegram bot yoki SMS orqali "aloqa" imitatsiyasi.',
  poc:'Qurilmadan telefonga BLE/Wi-Fi orqali ma’lumot uzatish.',
  proto:'Oflayn rejim, ma’lumotni navbatlash, aloqa uzilishini boshqarish.'},
 {id:'bio', name:'Biologik / tirik tizim', kw:['biolog','sintetik','tirik','o‘simlik','mikrob','genetik','oziq','ovqat','kasallik'], trl:4, cost:5,
  today:'Gidroponika/vertikal fermalar, fermentatsiya, mitseliy materiallari, laboratoriya diagnostik testlar, hujayra asosidagi oziq-ovqat (pilot).',
  gap:'Sintetik biologiya mahsulotlari tartibga solish va laboratoriya sharoitini talab qiladi; uyda tez emas.',
  parts:['Gidroponika to‘plami','Mikrob/mitseliy kulturalari (litsenziyali)','Diagnostik tasma/testlar'],
  tools:['Biologik xavfsiz laboratoriya yoki hamkor','Sterilizatsiya'], skills:['Biologiya mutaxassisi bilan hamkorlik','Normativ talablar'],
  mock:'Maket va jarayon diagrammasi; mutaxassis bilan intervyu.',
  poc:'Universitet/laboratoriya bilan hamkorlikda kichik tajriba.',
  proto:'Xavfsizlik va sertifikatsiya yo‘l xaritasi, kichik partiya.'},
 {id:'voice', name:'Ovoz / tabiiy interfeys', kw:['ovoz','nutq','gapir','interfeys','kirish','inklyuziv','imo','teginish'], trl:9, cost:1,
  today:'Ovozni matnga o‘girish (Whisper/Web Speech), matndan ovozga, teginish va imo-ishora tanish, ko‘p tilli (jumladan o‘zbek) modellar.',
  gap:'O‘zbek shevalari va shovqinli muhitda aniqlik hali pastroq bo‘lishi mumkin.',
  parts:['Mikrofon','Karnay','Telefon yoki Raspberry Pi'],
  tools:['Web Speech API','Whisper'], skills:['UX yozuvi','Foydalanuvchi sinovi'],
  mock:'Odam javob beradigan ovozli "sehrgar" sinovi.',
  poc:'Brauzerda ovoz buyrug‘ini tanib 3 ta amalni bajarish.',
  proto:'Shovqin, aksent va keksa foydalanuvchilar bilan sinov.'},
 {id:'health', name:'Salomatlik / kiyiladigan', kw:['salomatlik','sog‘liq','keks','puls','dori','kiyiladigan','shifokor','uyqu'], trl:8, cost:3,
  today:'Aqlli soat/bilaguzuklar (puls, SpO2, uyqu), uy diagnostikasi, dori eslatma qutilari, telemeditsina platformalari.',
  gap:'Tibbiy aniqlik va ruxsatnomalar (sertifikatsiya) murakkab; "wellness" va "tibbiy" farqi muhim.',
  parts:['PPG puls sensori','Akselerometr','Telefon ilovasi'],
  tools:['Foydalanuvchi sinovi','Tibbiy maslahatchi'], skills:['Maxfiylik (ma’lumot himoyasi)','Klinik tekshiruv asoslari'],
  mock:'Kunlik jadval va eslatma bilan "qo‘lda kuzatuv".',
  poc:'Puls/harakat ma’lumotini yig‘ib, g‘ayrioddiy holatda signal berish.',
  proto:'Yaqin odamlar/shifokor bilan bog‘lanish va ruxsatnomalar rejasi.'},
 {id:'transport', name:'Transport / parvoz', kw:['transport','parvoz','uchish','dron','avtomobil','mashina','yetkaz','logistika'], trl:6, cost:5,
  today:'Elektr velosiped/skuter, yetkazib berish dronlari (cheklangan ruxsat bilan), avtonom shaharlararo tajribalar, kargo robotlari.',
  gap:'Shaxsiy uchuvchi apparatlar va to‘liq avtonom haydash katta tartibga solish to‘siqlari bilan.',
  parts:['Elektr motor + batareya','Boshqaruv kontrolleri','GPS moduli'],
  tools:['Simulyator','Mahalliy qoidalar/ruxsatnomalar'], skills:['Aviatsiya/avto xavfsizligi','Boshqaruv tizimlari'],
  mock:'Simulyatsiya va video-stsenariy.',
  poc:'Kichik masshtabli maket (RC/dron) bilan sinov, ruxsat doirasida.',
  proto:'Xavfsizlik zaxiralari va qonuniy talablar bilan pilot.'},
 {id:'data', name:'Ma’lumot / xotira / maxfiylik', kw:['ma’lumot','maxfiy','xotira','blokcheyn','ishonch','bulut','platforma'], trl:9, cost:1,
  today:'Bulutli ma’lumotlar bazalari, qurilmada shifrlash, end-to-end shifrlash, blokcheyn (juda tanlab), federativ o‘rganish.',
  gap:'Ma’lumot egaligi va rozilikni foydalanuvchiga tushunarli qilish hamon dizayn muammosi.',
  parts:['Bulutli baza (Supabase/Firebase)','Shifrlash kutubxonalari'],
  tools:['Veb-ilova freymvorki'], skills:['Backend','Xavfsizlik va qonunlar (GDPR kabi)'],
  mock:'Jadval (Google Sheets) orqali "orqa tomon" imitatsiyasi.',
  poc:'Oddiy baza + foydalanuvchi roziligi ekrani.',
  proto:'Shifrlash, zaxira nusxa, ma’lumotni o‘chirish huquqi.'},
 {id:'community', name:'Hamjamiyat / xizmat modeli', kw:['hamjamiyat','ulashish','obuna','p2p','biznes','xizmat','mahalla','kooperativ'], trl:9, cost:1,
  today:'Obuna, p2p ulashish, kooperativlar, kraudfanding, mahalliy ishlab chiqarish (fab-lab), ochiq manba hamjamiyatlari.',
  gap:'Hamjamiyatni jalb qilish va ishonchni saqlash texnologiyadan qiyinroq.',
  parts:['Telegram guruh/kanal','Oddiy to‘lov tizimi','Landing sahifa'],
  tools:['Intervyu rejasi','Kraudfanding platformasi'], skills:['Hamjamiyat boshqaruvi','Marketing asoslari'],
  mock:'Landing sahifa + "oldindan buyurtma" ro‘yxati: talabni pul bilan sinash.',
  poc:'10–20 kishilik pilot guruh va qo‘lda xizmat ko‘rsatish.',
  proto:'Narx, to‘lov va hamkor tashkilotlar bilan barqaror model.'}
];
const TRL_TXT = t => t>=8?'Bugun mumkin':t>=6?'Qisman mumkin':t>=4?'Laboratoriya darajasida':'Hali tadqiqot bosqichida';
