/* ChemEdu — kimyoviy hisoblash vositalari (formalar + natijalar) */
(function () {
  const CE = (window.CE = window.CE || {});
  const { esc, num, fmt, mk, $, icon } = CE;
  const sub = (t) => CE.prettyFormula(t);
  const row = (k, v, u = '') => `<div class="r"><span>${k}</span><b>${v}${u ? ` <small>${u}</small>` : ''}</b></div>`;
  const box = (title, rows, extra = '') => `<div class="res"><h5>${title}</h5>${rows.join('')}${extra}</div>`;
  const need = (v, ...ks) => ks.forEach((k) => { if (!isFinite(v[k])) throw new Error(`«${k}» maydonini to'g'ri son bilan to'ldiring`); });
  const pos = (v, ...ks) => ks.forEach((k) => { if (!(v[k] > 0)) throw new Error(`«${k}» musbat bo'lishi kerak`); });
  const solveOne = (v, keys, label) => { const blanks = keys.filter((k) => !isFinite(v[k])); if (blanks.length !== 1) throw new Error(`${label}: aynan bitta maydonni bo'sh qoldiring (topiladigan kattalik). Hozir ${blanks.length} ta bo'sh.`); return blanks[0]; };
  const tt = { 90: [6.314, 2.92, 2.353, 2.132, 2.015, 1.943, 1.895, 1.86, 1.833, 1.812], 95: [12.706, 4.303, 3.182, 2.776, 2.571, 2.447, 2.365, 2.306, 2.262, 2.228], 99: [63.657, 9.925, 5.841, 4.604, 4.032, 3.707, 3.499, 3.355, 3.25, 3.169] };
  const tcrit = (df, p) => { if (df <= 10) return tt[p][df - 1]; const z = { 90: 1.645, 95: 1.96, 99: 2.576 }[p]; return z + (z ** 3 + z) / (4 * df); };
  const list = (s) => String(s).split(/[\s;]+/).map(num).filter((x) => isFinite(x));
  const UNITS = {
    'Massa': { mg: 1e-6, g: 1e-3, kg: 1, t: 1e3, mkg: 1e-9, funt: 0.45359237, unsiya: 0.028349523 },
    'Hajm': { 'mkL': 1e-9, mL: 1e-6, L: 1e-3, 'm³': 1, 'sm³': 1e-6, 'gallon (AQSH)': 3.785411784e-3 },
    'Bosim': { Pa: 1, kPa: 1e3, MPa: 1e6, bar: 1e5, atm: 101325, mmHg: 133.322368, torr: 133.322368, psi: 6894.757 },
    'Energiya': { J: 1, kJ: 1e3, cal: 4.184, kcal: 4184, eV: 1.602176634e-19, 'kW·soat': 3.6e6, 'L·atm': 101.325 },
    'Uzunlik': { nm: 1e-9, 'Å': 1e-10, 'mkm': 1e-6, mm: 1e-3, sm: 1e-2, m: 1, km: 1e3, dyuym: 0.0254 },
    'Modda miqdori': { mmol: 1e-3, mol: 1, kmol: 1e3 },
    'Zichlik': { 'g/mL': 1, 'kg/m³': 1e-3, 'g/L': 1e-3, 'kg/L': 1 }
  };
  const TEMPS = { 'K': [(x) => x, (x) => x], '°C': [(x) => x + 273.15, (x) => x - 273.15], '°F': [(x) => ((x - 32) * 5) / 9 + 273.15, (x) => ((x - 273.15) * 9) / 5 + 32] };

  const TOOLS = [
    { id: 'molar', name: 'Molyar massa', ico: 'calc', desc: "Formuladan molyar massa va elementlar tarkibi", f: [{ k: 'formula', l: 'Kimyoviy formula', t: 'text', d: 'Ca3(PO4)2', ph: 'Masalan: K4[Fe(CN)6], CuSO4·5H2O' }, { k: 'mass', l: 'Namuna massasi (ixtiyoriy)', u: 'g', opt: 1 }],
      run(v) { const c = CE.composition(v.formula), M = CE.molarMass(v.formula); const rows = c.map((x) => `<div class="bar-r"><span>${x.sym} × ${x.n}</span><i style="--w:${x.pct}%"></i><b>${fmt(x.mass, 5)} <small>g/mol</small></b><em>${fmt(x.pct, 4)} %</em></div>`);
        const ex = isFinite(v.mass) ? [row('Modda miqdori', fmt(v.mass / M), 'mol'), row('Zarralar soni', fmt((v.mass / M) * 6.02214076e23), 'dona')] : [];
        return box(`M(${sub(v.formula)})`, [row('Molyar massa', fmt(M, 6), 'g/mol'), ...ex], `<div class="bars">${rows.join('')}</div>`); } },
    { id: 'conc', name: 'Konsentratsiya', ico: 'drop', desc: 'M, ω, molallik, ppm, mol ulushi — o\'zaro o\'tkazish', f: [{ k: 'formula', l: 'Erigan modda formulasi', t: 'text', d: 'HCl' }, { k: 'rho', l: 'Eritma zichligi', u: 'g/mL', d: 1.19 }, { k: 'type', l: 'Ma\'lum kattalik', t: 'select', o: ['M — molyarlik (mol/L)', 'ω — massa ulushi (%)', 'm — molallik (mol/kg)', 'ppm (mg/kg)', 'x — mol ulushi'], d: 'ω — massa ulushi (%)' }, { k: 'value', l: 'Qiymati', d: 37 }],
      run(v) { need(v, 'rho', 'value'); pos(v, 'rho', 'value'); const MM = CE.molarMass(v.formula); const t = { M: 'M', 'ω': 'w', m: 'm', p: 'ppm', x: 'x' }[v.type[0]]; const r = CE.concConvert(t, v.value, MM, v.rho); if (t === 'w' && v.value >= 100) throw new Error('ω 100 % dan kichik bo\'lishi kerak'); if (t === 'x' && v.value >= 1) throw new Error('x 1 dan kichik bo\'lishi kerak');
        return box(`${sub(v.formula)} (M = ${fmt(MM, 5)} g/mol)`, [row('Molyarlik C', fmt(r.M), 'mol/L'), row('Massa ulushi ω', fmt(r.w), '%'), row('Molallik m', fmt(r.m), 'mol/kg'), row('ppm', fmt(r.ppm), 'mg/kg'), row('Mol ulushi x', fmt(r.x)), row('Normallik (bir asosli)', fmt(r.M), 'ekv/L')], '<p class="hint">Hisob: erituvchi — suv (18,015 g/mol), eritma zichligi o\'zgarmas deb olingan.</p>'); } },
    { id: 'ph', name: 'pH kalkulyator', ico: 'drop', desc: 'Kuchli/kuchsiz kislota-asos, bufer, pH ↔ [H⁺]', f: [{ k: 'type', l: 'Hisoblash turi', t: 'select', o: ['Kuchli kislota', 'Kuchli asos', 'Kuchsiz kislota', 'Kuchsiz asos', 'Bufer (Henderson–Hasselbalch)', 'pH → [H⁺], [OH⁻]'], d: 'Kuchsiz kislota' }, { k: 'c', l: 'Konsentratsiya C', u: 'mol/L', d: 0.1, opt: 1 }, { k: 'k', l: 'Ka yoki Kb (kuchsiz uchun)', d: '1.8e-5', opt: 1 }, { k: 'pka', l: 'pKa (bufer uchun)', d: 4.76, opt: 1 }, { k: 'ca', l: '[A⁻] — tuz (bufer)', u: 'mol/L', d: 0.1, opt: 1 }, { k: 'cha', l: '[HA] — kislota (bufer)', u: 'mol/L', d: 0.1, opt: 1 }, { k: 'ph', l: 'pH (teskari hisob uchun)', d: 7, opt: 1 }],
      run(v) { const T = v.type; let ph, extra = []; const kw = 1e-14;
        if (T.startsWith('Kuchli kislota')) { need(v, 'c'); pos(v, 'c'); ph = CE.phStrong(v.c, 'acid'); }
        else if (T.startsWith('Kuchli asos')) { need(v, 'c'); pos(v, 'c'); ph = CE.phStrong(v.c, 'base'); }
        else if (T.startsWith('Kuchsiz kislota')) { need(v, 'c', 'k'); pos(v, 'c', 'k'); const r = CE.phWeak(v.c, v.k, 'acid'); ph = r.ph; extra = [row('Dissotsiatsiya darajasi α', fmt(r.alpha * 100), '%'), row('pKa', fmt(-Math.log10(v.k)))]; }
        else if (T.startsWith('Kuchsiz asos')) { need(v, 'c', 'k'); pos(v, 'c', 'k'); const r = CE.phWeak(v.c, v.k, 'base'); ph = r.ph; extra = [row('Protonlanish darajasi α', fmt(r.alpha * 100), '%'), row('pKb', fmt(-Math.log10(v.k)))]; }
        else if (T.startsWith('Bufer')) { need(v, 'pka', 'ca', 'cha'); pos(v, 'ca', 'cha'); ph = v.pka + Math.log10(v.ca / v.cha); extra = [row('[A⁻]/[HA]', fmt(v.ca / v.cha)), row('Bufer sig\'imi (taxminiy)', fmt(2.303 * (v.ca * v.cha) / (v.ca + v.cha)), 'mol/L·pH')]; }
        else { need(v, 'ph'); ph = v.ph; }
        const H = Math.pow(10, -ph), OH = kw / H; return box('Natija', [row('pH', fmt(ph, 4)), row('pOH', fmt(14 - ph, 4)), row('[H⁺]', fmt(H), 'mol/L'), row('[OH⁻]', fmt(OH), 'mol/L'), ...extra, row('Muhit', ph < 6.95 ? 'kislotali' : ph > 7.05 ? 'ishqoriy' : 'neytral')], '<p class="hint">25 °C, Kw = 1·10⁻¹⁴, faollik koeffitsientlari hisobga olinmagan.</p>'); } },
    { id: 'dil', name: 'Suyultirish', ico: 'mix', desc: 'C₁V₁ = C₂V₂ — bitta noma\'lumni toping', f: [{ k: 'C1', l: 'C₁ — boshlang\'ich', u: 'M', d: 2, opt: 1 }, { k: 'V1', l: 'V₁ — olinadigan hajm', u: 'mL', opt: 1 }, { k: 'C2', l: 'C₂ — oxirgi', u: 'M', d: 0.5, opt: 1 }, { k: 'V2', l: 'V₂ — oxirgi hajm', u: 'mL', d: 250, opt: 1 }],
      run(v) { const b = solveOne(v, ['C1', 'V1', 'C2', 'V2'], 'Suyultirish'); const x = { C1: () => (v.C2 * v.V2) / v.V1, V1: () => (v.C2 * v.V2) / v.C1, C2: () => (v.C1 * v.V1) / v.V2, V2: () => (v.C1 * v.V1) / v.C2 }[b](); if (!(x > 0)) throw new Error('Qiymatlar musbat bo\'lishi kerak');
        const V1 = b === 'V1' ? x : v.V1, V2 = b === 'V2' ? x : v.V2; const extra = isFinite(V1) && isFinite(V2) ? [row('Qo\'shiladigan suv', fmt(V2 - V1), 'mL'), row('Suyultirish koeffitsienti', fmt(V2 / V1))] : [];
        return box('Natija', [row({ C1: 'C₁', V1: 'V₁', C2: 'C₂', V2: 'V₂' }[b], fmt(x), b[0] === 'C' ? 'M' : 'mL'), ...extra]); } },
    { id: 'titr', name: 'Titrlash', ico: 'flask', desc: 'Titrlash egri chizig\'i, ekvivalent nuqta va indikator', f: [{ k: 'kind', l: 'Analit', t: 'select', o: ['Kuchli kislota (HCl) ← NaOH', 'Kuchsiz kislota ← NaOH', 'Kuchli asos (NaOH) ← HCl', 'Kuchsiz asos ← HCl'], d: 'Kuchsiz kislota ← NaOH' }, { k: 'c', l: 'Analit konsentratsiyasi', u: 'M', d: 0.1 }, { k: 'v', l: 'Analit hajmi', u: 'mL', d: 25 }, { k: 'ct', l: 'Titrant konsentratsiyasi', u: 'M', d: 0.1 }, { k: 'k', l: 'Ka / Kb (kuchsiz uchun)', d: '1.8e-5', opt: 1 }],
      run(v) { need(v, 'c', 'v', 'ct'); pos(v, 'c', 'v', 'ct'); const acid = v.kind.includes('kislota'), strong = v.kind.startsWith('Kuchli'); if (!strong) { need(v, 'k'); pos(v, 'k'); }
        const r = CE.titrationCurve({ analyteKind: acid ? 'acid' : 'base', strong, c: v.c, v: v.v, ct: v.ct, k: v.k }); const veqmL = r.veq; const half = !strong ? CE.titrationCurve({ analyteKind: acid ? 'acid' : 'base', strong, c: v.c, v: v.v, ct: v.ct, k: v.k, points: 400 }).data.reduce((a, p) => (Math.abs(p[0] - veqmL / 2) < Math.abs(a[0] - veqmL / 2) ? p : a)) : null;
        const ind = r.phEq < 6 ? 'metil qizili (4,4–6,2)' : r.phEq <= 8 ? 'bromtimol ko\'ki (6,0–7,6)' : 'fenolftalein (8,2–10,0)'; const pts = r.data.map((p) => [p[0], p[1]]);
        const svg = CE.chart({ series: [{ d: pts }], xl: `V(titrant), mL`, yl: 'pH', ymin: 0, ymax: 14, marks: [{ x: veqmL, y: r.phEq, label: `ekv. nuqta pH ${fmt(r.phEq, 3)}` }], ariaLabel: 'Titrlash egri chizig\'i' });
        return box('Natija', [row('Ekvivalent hajm', fmt(veqmL), 'mL'), row('Boshlang\'ich pH', fmt(r.data[0][1], 3)), row('Ekvivalent nuqta pH', fmt(r.phEq, 3)), half ? row('Yarim titrlashda pH (≈ pKa/pKb)', fmt(half[1], 3)) : '', row('Mos indikator', ind), row('Oxirgi pH (2·Vekv)', fmt(r.data[r.data.length - 1][1], 3))].filter(Boolean), svg); } },
    { id: 'gas', name: 'Ideal gaz (PV=nRT)', ico: 'thermo', desc: 'Bitta kattalikni bo\'sh qoldiring — topiladi', f: [{ k: 'P', l: 'Bosim P', d: 1, opt: 1, unit: { k: 'Pu', o: ['atm', 'kPa', 'bar', 'mmHg'] } }, { k: 'V', l: 'Hajm V', opt: 1, unit: { k: 'Vu', o: ['L', 'mL', 'm³'] } }, { k: 'n', l: 'Modda miqdori n', u: 'mol', d: 1, opt: 1 }, { k: 'T', l: 'Harorat T', d: 273.15, opt: 1, unit: { k: 'Tu', o: ['K', '°C', '°F'] } }],
      run(v) { const toAtm = { atm: 1, kPa: 1 / 101.325, bar: 0.986923, mmHg: 1 / 760 }[v.Pu], toL = { L: 1, mL: 1e-3, 'm³': 1e3 }[v.Vu]; const P = v.P * toAtm, V = v.V * toL, n = v.n, T = TEMPS[v.Tu][0](v.T); const R = CE.R_GAS;
        const b = solveOne({ P, V, n, T }, ['P', 'V', 'n', 'T'], 'Ideal gaz'); let out;
        if (b === 'P') { const p = (n * R * T) / V; out = row('P', fmt(p / toAtm), v.Pu) + row('P', fmt(p * 101.325), 'kPa'); }
        else if (b === 'V') { const x = (n * R * T) / P; out = row('V', fmt(x / toL), v.Vu) + row('V', fmt(x), 'L'); }
        else if (b === 'n') { const x = (P * V) / (R * T); out = row('n', fmt(x), 'mol') + row('Zarralar', fmt(x * 6.02214076e23)); }
        else { const x = (P * V) / (n * R); out = row('T', fmt(TEMPS[v.Tu][1](x)), v.Tu) + row('T', fmt(x), 'K'); }
        if (T <= 0 && b !== 'T') throw new Error('Harorat absolyut noldan yuqori bo\'lishi kerak'); return box('Natija', [out], `<p class="hint">R = 0,082057 L·atm/(mol·K). ${b === 'n' ? '' : 'Ideal gaz yaqinlashuvi.'}</p>`); } },
    { id: 'stoich', name: 'Stexiometriya', ico: 'scale', desc: 'Cheklovchi reagent, nazariy va amaliy unum', f: [{ k: 'eq', l: 'Reaksiya tenglamasi', t: 'text', d: 'HCl + CaCO3 -> CaCl2 + CO2 + H2O' }, { k: 'given', l: 'Berilgan miqdorlar (har bir reaktiv)', t: 'textarea', d: 'HCl = 10 g\nCaCO3 = 0.08 mol', ph: 'HCl = 10 g, CaCO3 = 0.08 mol' }, { k: 'actual', l: 'Amaliy hosil (birinchi mahsulot), g', opt: 1 }],
      run(v) { const b = CE.balance(v.eq); const co = b.coefficients; const given = {}; String(v.given).split(/[\n,;]+/).map((s) => s.trim()).filter(Boolean).forEach((s) => { const m = /^(.+?)\s*=\s*([\d.,eE+-]+)\s*(g|mol|mg|kg)?$/.exec(s); if (!m) throw new Error(`«${s}» o'qilmadi. Format: HCl = 10 g`); const f = m[1].trim(); const q = num(m[2]); const u = m[3] || 'g'; given[f] = u === 'mol' ? q : (u === 'mg' ? q / 1000 : u === 'kg' ? q * 1000 : q) / CE.molarMass(f); });
        let lim = null; b.reactants.forEach((s, i) => { if (given[s] === undefined) return; const ext = given[s] / co[i]; if (!lim || ext < lim.ext) lim = { s, ext, i }; });
        if (!lim) throw new Error('Kamida bitta reaktiv uchun miqdor kiriting'); const missing = b.reactants.filter((s) => given[s] === undefined);
        const rowsR = b.reactants.map((s, i) => { const need = lim.ext * co[i]; const have = given[s]; const M = CE.molarMass(s); return `<tr><td>${sub(s)}</td><td>${fmt(have)}</td><td>${fmt(need)}</td><td>${have === undefined ? '—' : fmt(have - need)}</td><td>${fmt(have === undefined ? need * M : (have - need) * M)}</td></tr>`; });
        const rowsP = b.products.map((s, i) => { const n = lim.ext * co[b.reactants.length + i], M = CE.molarMass(s); return `<tr><td>${sub(s)}</td><td>${fmt(n)}</td><td>${fmt(n * M)}</td><td>${fmt(n * 22.414)}</td></tr>`; });
        const p0 = b.products[0], th = lim.ext * co[b.reactants.length] * CE.molarMass(p0); const yld = isFinite(v.actual) ? row(`Unum (${sub(p0)})`, fmt((v.actual / th) * 100), '%') : '';
        return box('Natija', [row('Balanslangan tenglama', b.html), row('Cheklovchi reagent', sub(lim.s)), missing.length ? row('Mo\'l deb olingan', missing.map(sub).join(', ')) : '', yld].filter(Boolean), `<div class="tbl-w"><table class="tbl"><thead><tr><th>Reaktiv</th><th>Berilgan, mol</th><th>Sarflanadi, mol</th><th>Qoladi, mol</th><th>Qoldiq, g</th></tr></thead><tbody>${rowsR.join('')}</tbody></table></div><div class="tbl-w"><table class="tbl"><thead><tr><th>Mahsulot</th><th>mol</th><th>g</th><th>L (n.sh.)</th></tr></thead><tbody>${rowsP.join('')}</tbody></table></div>`); } },
    { id: 'mix', name: 'Aralashma', ico: 'mix', desc: 'Eritmalar va haroratlarni aralashtirish', f: [{ k: 'C1', l: 'C₁ (1-eritma)', u: 'M', d: 1, opt: 1 }, { k: 'V1', l: 'V₁', u: 'mL', d: 100, opt: 1 }, { k: 'C2', l: 'C₂ (2-eritma)', u: 'M', d: 0.2, opt: 1 }, { k: 'V2', l: 'V₂', u: 'mL', d: 200, opt: 1 }, { k: 'T1', l: 'T₁', u: '°C', opt: 1 }, { k: 'T2', l: 'T₂', u: '°C', opt: 1 }],
      run(v) { const rows = []; if (isFinite(v.C1) && isFinite(v.V1) && isFinite(v.C2) && isFinite(v.V2)) { const V = v.V1 + v.V2, C = (v.C1 * v.V1 + v.C2 * v.V2) / V; rows.push(row('Umumiy hajm', fmt(V), 'mL'), row('Yakuniy konsentratsiya', fmt(C), 'M'), row('Umumiy modda miqdori', fmt((v.C1 * v.V1 + v.C2 * v.V2) / 1000), 'mol')); } if (isFinite(v.T1) && isFinite(v.T2) && isFinite(v.V1) && isFinite(v.V2)) rows.push(row('Yakuniy harorat', fmt((v.V1 * v.T1 + v.V2 * v.T2) / (v.V1 + v.V2)), '°C')); if (!rows.length) throw new Error('Kamida C₁,V₁,C₂,V₂ ni to\'ldiring'); return box('Natija', rows, '<p class="hint">Hajmlar additiv, zichlik va issiqlik sig\'imi bir xil deb olingan.</p>'); } },
    { id: 'dens', name: 'Zichlik', ico: 'cube', desc: 'ρ = m / V', f: [{ k: 'm', l: 'Massa m', u: 'g', d: 27, opt: 1 }, { k: 'V', l: 'Hajm V', u: 'mL', d: 10, opt: 1 }, { k: 'rho', l: 'Zichlik ρ', u: 'g/mL', opt: 1 }],
      run(v) { const b = solveOne(v, ['m', 'V', 'rho'], 'Zichlik'); const x = b === 'm' ? v.rho * v.V : b === 'V' ? v.m / v.rho : v.m / v.V; if (!(x > 0)) throw new Error('Qiymatlar musbat bo\'lishi kerak'); return box('Natija', [row({ m: 'Massa', V: 'Hajm', rho: 'Zichlik' }[b], fmt(x), { m: 'g', V: 'mL', rho: 'g/mL' }[b]), b === 'rho' ? row('kg/m³', fmt(x * 1000)) : '']); } },
    { id: 'prep', name: 'Eritma tayyorlash', ico: 'flask', desc: 'Qattiq moddadan yoki konsentrlangan eritmadan', f: [{ k: 'src', l: 'Boshlang\'ich modda', t: 'select', o: ['Qattiq modda', 'Konsentrlangan eritma'], d: 'Qattiq modda' }, { k: 'formula', l: 'Formula', t: 'text', d: 'NaOH' }, { k: 'c', l: 'Kerakli konsentratsiya', u: 'M', d: 0.1 }, { k: 'v', l: 'Kerakli hajm', u: 'mL', d: 500 }, { k: 'pur', l: 'Tozalik / ω (konsentrlangan eritma uchun ω)', u: '%', d: 98 }, { k: 'rho', l: 'Konsentrlangan eritma zichligi', u: 'g/mL', d: 1.19, opt: 1 }],
      run(v) { need(v, 'c', 'v', 'pur'); pos(v, 'c', 'v', 'pur'); if (v.pur > 100) throw new Error('Tozalik 100 % dan oshmasin'); const MM = CE.molarMass(v.formula), n = (v.c * v.v) / 1000;
        if (v.src === 'Qattiq modda') { const m = (n * MM) / (v.pur / 100); return box('Natija', [row('Kerakli massa', fmt(m, 4), 'g'), row('Sof modda', fmt(n * MM, 4), 'g'), row('Modda miqdori', fmt(n), 'mol')], `<ol class="steps"><li>${fmt(m, 4)} g ${sub(v.formula)} ni analitik tarozida torting.</li><li>${v.v} mL li o'lchov kolbasiga o'tkazing, 1/2 hajm suvda eriting.</li><li>Belgigacha suv qo'shing va aralashtiring.</li></ol>`); }
        need(v, 'rho'); pos(v, 'rho'); const cs = (v.pur / 100) * v.rho * 1000 / MM; const Vs = (n / cs) * 1000; return box('Natija', [row('Konsentrlangan eritma molyarligi', fmt(cs), 'M'), row('Olinadigan hajm', fmt(Vs, 4), 'mL'), row('Qo\'shiladigan suv (≈)', fmt(v.v - Vs, 4), 'mL')], `<ol class="steps"><li>Kolbaga taxminan 1/2 hajm suv soling.</li><li>${fmt(Vs, 3)} mL konsentrlangan eritmani sekin qo'shing (kislota — suvga!).</li><li>Sovigach, belgigacha suv bilan to'ldiring.</li></ol>`); } },
    { id: 'enth', name: 'Reaksiya issiqligi', ico: 'thermo', desc: 'ΔH° (Gess qonuni) va kalorimetriya', f: [{ k: 'eq', l: 'Reaksiya tenglamasi', t: 'text', d: 'CH4 + O2 -> CO2 + H2O', opt: 1 }, { k: 'm', l: 'Kalorimetr: suv massasi', u: 'g', opt: 1 }, { k: 'dT', l: 'ΔT', u: '°C', opt: 1 }, { k: 'c', l: 'Solishtirma issiqlik sig\'imi', u: 'J/(g·K)', d: 4.18, opt: 1 }],
      run(v) { const rows = []; let extra = ''; if (String(v.eq).trim()) { const r = CE.reactionEnthalpy(v.eq); if (r.miss.length) throw new Error(`ΔHf° ma'lumoti yo'q: ${r.miss.join(', ')}`); rows.push(row('Balanslangan', r.balanced.html), row('ΔH°(reaksiya)', fmt(r.dh, 5), 'kJ'), row('Xarakter', r.dh < 0 ? 'ekzotermik (issiqlik ajraladi)' : 'endotermik (issiqlik yutiladi)')); extra = '<p class="hint">H₂O — suyuq holat uchun olindi (ΔHf° = −285,8 kJ/mol). Standart sharoit, 298 K.</p>'; }
        if (isFinite(v.m) && isFinite(v.dT) && isFinite(v.c)) { const q = v.m * v.c * v.dT; rows.push(row('q = m·c·ΔT', fmt(q, 4), 'J'), row('', fmt(q / 1000, 4), 'kJ')); } if (!rows.length) throw new Error('Tenglamani yoki kalorimetr ma\'lumotlarini kiriting'); return box('Natija', rows, extra); } },
    { id: 'calib', name: 'Kalibrlash grafigi', ico: 'trend', desc: 'Chiziqli regressiya, R², noma\'lum konsentratsiya (Ber qonuni)', f: [{ k: 'data', l: 'Standartlar: konsentratsiya, optik zichlik (har qatorda)', t: 'textarea', d: '0.00 0.002\n0.10 0.121\n0.20 0.243\n0.30 0.358\n0.40 0.482', ph: 'c  A' }, { k: 'Ax', l: 'Noma\'lum namuna optik zichligi A', d: 0.3, opt: 1 }],
      run(v) { const pts = String(v.data).split('\n').map((l) => list(l)).filter((a) => a.length >= 2).map((a) => [a[0], a[1]]); if (pts.length < 3) throw new Error('Kamida 3 ta nuqta kiriting'); const n = pts.length, sx = pts.reduce((a, p) => a + p[0], 0), sy = pts.reduce((a, p) => a + p[1], 0), sxx = pts.reduce((a, p) => a + p[0] ** 2, 0), sxy = pts.reduce((a, p) => a + p[0] * p[1], 0); const sl = (n * sxy - sx * sy) / (n * sxx - sx * sx), ic = (sy - sl * sx) / n; const ym = sy / n; const sst = pts.reduce((a, p) => a + (p[1] - ym) ** 2, 0), ssr = pts.reduce((a, p) => a + (p[1] - (sl * p[0] + ic)) ** 2, 0); const r2 = 1 - ssr / sst; const se = Math.sqrt(ssr / (n - 2)); const xs = pts.map((p) => p[0]); const x0 = Math.min(...xs), x1 = Math.max(...xs);
        const rows = [row('Tenglama', `A = ${fmt(sl, 5)}·c ${ic < 0 ? '−' : '+'} ${fmt(Math.abs(ic), 4)}`), row('R²', fmt(r2, 5)), row('Qoldiq SO', fmt(se, 3)), row('LOD (3.3·s/m)', fmt((3.3 * se) / Math.abs(sl), 3)), row('LOQ (10·s/m)', fmt((10 * se) / Math.abs(sl), 3))]; const ser = [{ d: pts, line: false, dots: true }, { d: [[x0, sl * x0 + ic], [x1, sl * x1 + ic]], dash: true }]; const marks = [];
        if (isFinite(v.Ax)) { const cx = (v.Ax - ic) / sl; rows.push(row('Noma\'lum konsentratsiya', fmt(cx, 4))); marks.push({ x: cx, y: v.Ax, label: `c = ${fmt(cx, 3)}` }); }
        return box('Regressiya natijasi', rows, CE.chart({ series: ser, xl: 'Konsentratsiya', yl: 'A', marks, ariaLabel: 'Kalibrlash grafigi' }) + (r2 < 0.99 ? '<p class="hint warn">R² &lt; 0,99 — chiziqlilik yetarli emas, standartlarni tekshiring.</p>' : '')); } },
    { id: 'stat', name: 'Statistika', ico: 'sigma', desc: "O'rtacha, SO, ishonch oralig'i, Q-test", f: [{ k: 'data', l: 'Parallel natijalar (probel/vergul bilan)', t: 'textarea', d: '24.95 25.05 25.00 25.10 24.90', ph: '25.00 25.05 24.95' }, { k: 'p', l: 'Ishonchlilik', t: 'select', o: ['90', '95', '99'], d: '95' }],
      run(v) { const a = list(v.data); if (a.length < 3) throw new Error('Kamida 3 ta qiymat kiriting'); const n = a.length, mean = a.reduce((x, y) => x + y, 0) / n, sd = Math.sqrt(a.reduce((x, y) => x + (y - mean) ** 2, 0) / (n - 1)); const t = tcrit(n - 1, +v.p), ci = (t * sd) / Math.sqrt(n); const s = [...a].sort((x, y) => x - y); const rng = s[n - 1] - s[0]; const rows = [row('n', n), row('O\'rtacha', fmt(mean, 6)), row('Standart og\'ish s', fmt(sd, 4)), row('Nisbiy SO (RSD)', fmt((sd / mean) * 100, 3), '%'), row(`${v.p} % ishonch oralig'i`, `${fmt(mean, 5)} ± ${fmt(ci, 3)}`), row('Variatsiya kengligi', fmt(rng))];
        const Qc = { 3: .97, 4: .829, 5: .71, 6: .625, 7: .568, 8: .526, 9: .493, 10: .466 }[n]; let q = ''; if (Qc && rng > 0) { const qh = (s[1] - s[0]) / rng, ql = (s[n - 1] - s[n - 2]) / rng; const [qq, val] = qh > ql ? [qh, s[0]] : [ql, s[n - 1]]; q = row('Q-test (95 %)', `Q = ${fmt(qq, 3)} ${qq > Qc ? `> ${Qc} → ${val} chetlanish (chiqarib tashlash mumkin)` : `≤ ${Qc} → chetlanish yo'q`}`); }
        return box('Natija', [...rows, q].filter(Boolean)); } },
    { id: 'units', name: 'Birliklar konvertori', ico: 'rule', desc: 'Massa, hajm, bosim, energiya, harorat va boshqalar', custom: true }
  ];

  function renderTool(tool, root) {
    root.innerHTML = '';
    const head = mk(`<div class="tool-head"><span class="tico">${icon(tool.ico)}</span><div><h3>${esc(tool.name)}</h3><p>${esc(tool.desc)}</p></div></div>`);
    root.appendChild(head);
    if (tool.custom) { renderUnits(root); return; }
    const form = mk(`<form class="tool-form" autocomplete="off">${tool.f.map((f) => {
      const id = `f-${tool.id}-${f.k}`;
      const inp = f.t === 'select' ? `<select id="${id}" name="${f.k}">${f.o.map((o) => `<option ${o === f.d ? 'selected' : ''}>${esc(o)}</option>`).join('')}</select>`
        : f.t === 'textarea' ? `<textarea id="${id}" name="${f.k}" rows="4" placeholder="${esc(f.ph || '')}">${esc(f.d || '')}</textarea>`
          : `<input id="${id}" name="${f.k}" type="text" inputmode="${f.t === 'text' ? 'text' : 'decimal'}" value="${esc(f.d === undefined ? '' : f.d)}" placeholder="${f.opt ? 'bo\'sh' : ''}${f.ph ? esc(f.ph) : ''}">`;
      const un = f.unit ? `<select class="unit" name="${f.unit.k}">${f.unit.o.map((o) => `<option>${esc(o)}</option>`).join('')}</select>` : f.u ? `<em>${esc(f.u)}</em>` : '';
      return `<label class="${f.t === 'textarea' || f.t === 'text' ? 'full' : ''}"><span>${esc(f.l)}</span><div class="inp">${inp}${un}</div></label>`;
    }).join('')}<div class="full row-btn"><button class="btn primary" type="submit">${icon('calc')}Hisoblash</button><button class="btn ghost" type="button" data-copy>${icon('copy')}Natijani nusxalash</button></div></form>`);
    const out = mk('<div class="tool-out" aria-live="polite"></div>');
    root.append(form, out);
    const run = () => {
      const raw = Object.fromEntries(new FormData(form)); const v = {};
      tool.f.forEach((f) => { v[f.k] = f.t === 'text' || f.t === 'select' || f.t === 'textarea' ? raw[f.k] : num(raw[f.k]); if (f.unit) v[f.unit.k] = raw[f.unit.k]; });
      try { out.innerHTML = tool.run(v); out.classList.remove('err'); CE.db.log('calc', 'blue', `${tool.name}: hisoblash bajarildi`); }
      catch (e) { out.classList.add('err'); out.innerHTML = `<div class="res err">${icon('warn')}<span>${esc(e.message)}</span></div>`; }
    };
    form.addEventListener('submit', (e) => { e.preventDefault(); run(); });
    $('[data-copy]', form).onclick = () => CE.copy(out.innerText.trim() || '');
    run();
  }
  function renderUnits(root) {
    const w = mk(`<div class="tool-form"><label><span>Kategoriya</span><div class="inp"><select data-c>${[...Object.keys(UNITS), 'Harorat'].map((k) => `<option>${k}</option>`).join('')}</select></div></label><label><span>Qiymat</span><div class="inp"><input data-v value="1" inputmode="decimal"></div></label><label><span>Qaysi birlikdan</span><div class="inp"><select data-f></select></div></label><label><span>Qaysi birlikka</span><div class="inp"><select data-t></select></div></label></div>`);
    const out = mk('<div class="tool-out"></div>'); root.append(w, out);
    const sel = (s) => $(s, w); const fill = () => { const k = sel('[data-c]').value; const keys = k === 'Harorat' ? Object.keys(TEMPS) : Object.keys(UNITS[k]); [sel('[data-f]'), sel('[data-t]')].forEach((s, i) => { s.innerHTML = keys.map((u, j) => `<option ${j === (i ? Math.min(1, keys.length - 1) : 0) ? 'selected' : ''}>${esc(u)}</option>`).join(''); }); calc(); };
    const calc = () => { const k = sel('[data-c]').value, v = num(sel('[data-v]').value), f = sel('[data-f]').value, t = sel('[data-t]').value; if (!isFinite(v)) { out.innerHTML = '<div class="res err">Sonni kiriting</div>'; return; }
      let r; if (k === 'Harorat') r = TEMPS[t][1](TEMPS[f][0](v)); else r = (v * UNITS[k][f]) / UNITS[k][t]; const all = k === 'Harorat' ? Object.keys(TEMPS).map((u) => row(u, fmt(TEMPS[u][1](TEMPS[f][0](v)), 6))) : Object.keys(UNITS[k]).map((u) => row(u, fmt((v * UNITS[k][f]) / UNITS[k][u], 6)));
      out.innerHTML = box(`${fmt(v)} ${f} = ${fmt(r, 6)} ${t}`, all); };
    w.addEventListener('input', calc); sel('[data-c]').addEventListener('change', fill); fill();
  }

  CE.TOOLS = TOOLS; CE.renderTool = renderTool;
})();
