/* ChemEdu — sahifalar (2): kimyoviy ma'lumotlar, vositalar, talabalar, topshiriqlar, testlar, AI, shablonlar, konferensiyalar, taqvim, loyihalar, sozlamalar */
(function () {
  const CE = (window.CE = window.CE || {});
  const { esc, icon, mk, $, $$, db, uid, fmt, toast, modal, pageHead, empty, stat, section } = CE;
  const V = CE.views;
  const fieldOf = (id) => CE.FIELDS.find((f) => f.id === id);
  const csv = (rows) => '﻿' + rows.map((r) => r.map((x) => `"${String(x ?? '').replace(/"/g, '""')}"`).join(';')).join('\n');
  const grade = (pct) => (pct >= 86 ? 5 : pct >= 71 ? 4 : pct >= 56 ? 3 : 2);
  (db.s.qbank || []).forEach((q) => CE.TESTS.push(q));

  // ---------- Kimyoviy ma'lumotlar ----------
  const groupOf = (e) => (e.row <= 7 && e.cat !== 'lan' && e.cat !== 'act' ? e.col : '—');
  function periodic(root) {
    let mode = 'cat', q = '', cat = 'all';
    root.innerHTML = `<div class="toolbar"><input type="search" placeholder="Element: nom, belgi yoki raqam…" aria-label="Elementni qidirish"><div class="chips pick modes">${[['cat', 'Kategoriya'], ['en', 'Elektromanfiylik'], ['mass', 'Atom massasi']].map(([k, l]) => `<button class="chip ${k === mode ? 'on' : ''}" data-m="${k}">${l}</button>`).join('')}</div></div><div class="legend">${Object.entries(CE.CATS).map(([k, v]) => `<button class="lg c-${k}" data-c="${k}"><i></i>${v}</button>`).join('')}</div><div class="ptable-w"><div class="ptable"></div></div>`;
    const grid = $('.ptable', root);
    const paint = (e) => { if (mode === 'en') return e.en ? `style="--bg:hsl(${220 - (e.en / 4) * 200} 75% ${92 - (e.en / 4) * 38}%)"` : 'style="--bg:#e3e8f2"'; if (mode === 'mass') return `style="--bg:hsl(${215} 80% ${96 - (e.mass / 300) * 52}%)"`; return ''; };
    const draw = () => {
      const match = (e) => (!q || CE.norm(e.name + ' ' + e.sym + ' ' + e.z).includes(CE.norm(q))) && (cat === 'all' || e.cat === cat);
      grid.innerHTML = CE.ELEMENTS.map((e) => `<button class="el c-${mode === 'cat' ? e.cat : 'x'} ${match(e) ? '' : 'dim'}" ${paint(e)} style="grid-row:${e.row >= 8 ? e.row + 1 : e.row};grid-column:${e.col};${paint(e).replace(/^style="|"$/g, '')}" data-z="${e.z}" aria-label="${esc(e.name)}"><small>${e.z}</small><b>${e.sym}</b><span>${esc(e.name)}</span><em>${fmt(e.mass, 5)}</em></button>`).join('') + `<div class="el ph c-lan" style="grid-row:6;grid-column:3"><b>57–71</b></div><div class="el ph c-act" style="grid-row:7;grid-column:3"><b>89–103</b></div>`;
      $$('[data-z]', grid).forEach((b) => b.onclick = () => elementModal(CE.ELEMENTS[+b.dataset.z - 1]));
    };
    $('input', root).oninput = (e) => { q = e.target.value; draw(); };
    $$('[data-m]', root).forEach((b) => b.onclick = () => { mode = b.dataset.m; $$('[data-m]', root).forEach((x) => x.classList.toggle('on', x === b)); draw(); });
    $$('[data-c]', root).forEach((b) => b.onclick = () => { cat = cat === b.dataset.c ? 'all' : b.dataset.c; $$('[data-c]', root).forEach((x) => x.classList.toggle('on', x.dataset.c === cat)); draw(); });
    draw();
  }
  function elementModal(e) {
    modal({ title: `${e.name} (${e.sym})`, wide: true, body: `<div class="el-d"><div class="el-big c-${e.cat}"><small>${e.z}</small><b>${e.sym}</b><span>${esc(e.name)}</span><em>${fmt(e.mass, 6)}</em></div><div class="kv"><span>Atom raqami</span><b>${e.z}</b><span>Atom massasi</span><b>${fmt(e.mass, 6)} u</b><span>Davr / guruh</span><b>${e.period} / ${groupOf(e)}</b><span>Kategoriya</span><b>${CE.CATS[e.cat]}</b><span>Elektron konfiguratsiya</span><b>${esc(CE.electronConfig(e.z))}</b><span>Elektromanfiylik</span><b>${e.en || "ma'lumot yo'q"}</b></div></div>`, actions: [{ label: 'Molyar massa kalkulyatori', cls: 'ghost', fn: () => { location.hash = '#/tools/molar'; } }, { label: 'Yopish', cls: 'primary' }] });
  }
  CE.elementModal = elementModal;
  V['chem-info'] = (root, sub, qs) => {
    const tab = ['periodic', 'molecule', 'reaction', 'sds', 'compounds'].includes(sub) ? sub : 'periodic'; const params = new URLSearchParams(qs || '');
    root.innerHTML = pageHead("Kimyoviy ma'lumotlar", 'Davriy jadval, molekulalar, reaksiyalar va xavfsizlik ma\'lumotlari') + `<nav class="tabs big">${[['periodic', 'Davriy jadval'], ['molecule', 'Molekula 2D/3D'], ['reaction', 'Reaksiya balanslash'], ['sds', 'SDS / Xavfsizlik'], ['compounds', 'Birikmalar bazasi']].map(([k, l]) => `<a href="#/chem-info/${k}" class="${k === tab ? 'on' : ''}">${l}</a>`).join('')}</nav><div class="tab-body"></div>`;
    const body = $('.tab-body', root);
    if (tab === 'periodic') { periodic(body); if (params.get('el')) { const e = CE.BYSYM[params.get('el')]; if (e) elementModal(e); } }
    else if (tab === 'molecule') { const s = section('mol-w big'); body.appendChild(s); CE.W.molecule(s, { full: true, q: params.get('q') || 'Aspirin' }); }
    else if (tab === 'reaction') { body.innerHTML = '<div class="split wide"><section class="card panel react-p"></section><section class="card panel"></section></div>'; const [a, b] = $$('.panel', body); CE.W.reaction(a); CE.renderTool(CE.TOOLS.find((t) => t.id === 'stoich'), b); }
    else if (tab === 'sds') {
      let sel = 0, q = '';
      body.innerHTML = `<div class="sds"><aside class="card panel"><input type="search" placeholder="Modda qidirish…" aria-label="Qidirish"><ul class="sds-list"></ul></aside><section class="card panel sds-d"></section></div><p class="hint">Diqqat: bu qisqacha ma'lumotnoma. Ishlashdan oldin ta'minotchining rasmiy SDS hujjatini o'qing.</p>`;
      const drawL = () => { const L = CE.SDS.map((s, i) => ({ s, i })).filter(({ s }) => CE.norm(s.n + s.f + s.cas).includes(CE.norm(q))); $('.sds-list', body).innerHTML = L.map(({ s, i }) => `<li><button class="${i === sel ? 'on' : ''}" data-i="${i}"><b>${esc(s.n)}</b><small>${CE.prettyFormula(s.f)} · ${s.cas}</small></button></li>`).join('') || '<li class="empty-s">Topilmadi</li>'; $$('[data-i]', body).forEach((b) => b.onclick = () => { sel = +b.dataset.i; drawL(); drawD(); }); };
      const drawD = () => { const s = CE.SDS[sel]; $('.sds-d', body).innerHTML = `<h2>${esc(s.n)} <small>${CE.prettyFormula(s.f)}</small></h2><p class="cas">CAS: ${s.cas} · M = ${(() => { try { return fmt(CE.molarMass(s.f), 5) + ' g/mol'; } catch (e) { return '—'; } })()}</p><div class="ghs">${s.g.map((g) => `<span class="ghs-i" style="--c:${CE.GHS[g][1]}"><i>${icon(g === 'yonuvchan' ? 'bolt' : g === 'atrof' ? 'drop' : g === 'korroziv' ? 'flask' : 'warn')}</i>${CE.GHS[g][0]}</span>`).join('')}</div><h5>Xavf iboralari (H)</h5><ul>${s.h.map((x) => `<li>${esc(x)}</li>`).join('')}</ul><h5>Shaxsiy himoya vositalari</h5><p>${esc(s.ppe)}</p><h5>Birinchi yordam</h5><p>${esc(s.aid)}</p><h5>Saqlash</h5><p>${esc(s.st)}</p><div class="row-btn"><a class="btn ghost" target="_blank" rel="noopener" href="https://pubchem.ncbi.nlm.nih.gov/#query=${encodeURIComponent(s.cas)}">${icon('ext')}PubChem</a></div>`; };
      $('input', body).oninput = (e) => { q = e.target.value; drawL(); }; drawL(); drawD();
    } else {
      let q = '';
      body.innerHTML = `<div class="toolbar"><input type="search" placeholder="Birikma qidirish…" aria-label="Qidirish"></div><div class="tbl-w"><table class="tbl"><thead><tr><th>Nomi</th><th>Formula</th><th>M, g/mol</th><th>SMILES</th><th></th></tr></thead><tbody></tbody></table></div>`;
      const draw = () => { $('tbody', body).innerHTML = CE.MOLDB.filter((d) => CE.norm(d.name + d.formula + d.syn.join(' ')).includes(CE.norm(q))).map((d) => `<tr><td><b>${esc(d.name)}</b></td><td>${CE.prettyFormula(d.formula)}</td><td>${fmt(CE.molarMass(d.formula), 5)}</td><td><code>${esc(d.smiles)}</code></td><td class="act"><a class="btn ghost sm" href="#/chem-info/molecule?q=${encodeURIComponent(d.name)}">${icon('mol')}3D</a></td></tr>`).join(''); };
      $('input', body).oninput = (e) => { q = e.target.value; draw(); }; draw();
    }
  };

  // ---------- Vositalar ----------
  V.tools = (root, sub) => {
    const cur = CE.TOOLS.find((t) => t.id === sub) || CE.TOOLS[0];
    root.innerHTML = pageHead('Hisoblashlar va vositalar', '14 ta kimyoviy kalkulyator — aniq formulalar va bosqichma-bosqich natijalar') + `<div class="tools-page"><aside class="tool-nav">${CE.TOOLS.map((t) => `<a href="#/tools/${t.id}" class="${t.id === cur.id ? 'on' : ''}"><span>${icon(t.ico)}</span><div><b>${esc(t.name)}</b><small>${esc(t.desc)}</small></div></a>`).join('')}</aside><section class="card panel tool-panel"></section></div>`;
    CE.renderTool(cur, $('.tool-panel', root));
  };

  // ---------- Talabalar ----------
  const studentAvg = (s) => { let got = 0, max = 0; db.s.assignments.forEach((a) => { if (a.grades[s.id] !== undefined) { got += a.grades[s.id]; max += a.max; } }); return max ? Math.round((got / max) * 100) : null; };
  V.students = (root) => {
    let q = '', g = 'all';
    root.innerHTML = pageHead('Talabalar boshqaruvi', "Guruhlar, o'zlashtirish va aloqa ma'lumotlari", `<button class="btn ghost" data-imp>${icon('plus')}Import</button><button class="btn ghost" data-exp>${icon('download')}CSV</button><button class="btn primary" data-add>${icon('plus')}Talaba qo'shish</button>`) + `<div class="stats"></div><div class="toolbar"><input type="search" placeholder="Talaba qidirish…" aria-label="Qidirish"><div class="chips pick groups"></div></div><div class="tbl-w"><table class="tbl"><thead><tr><th>Talaba</th><th>Guruh</th><th>E-pochta</th><th>O'zlashtirish</th><th></th></tr></thead><tbody></tbody></table></div>`;
    const form = (s) => CE.formModal({ title: s ? 'Talabani tahrirlash' : "Talaba qo'shish", values: s || { group: 'KT-21' }, fields: [{ k: 'name', label: 'F.I.Sh.', req: 1, full: 1 }, { k: 'group', label: 'Guruh', req: 1 }, { k: 'email', label: 'E-pochta', type: 'email' }], onSubmit: (d) => { if (s) Object.assign(s, d); else db.s.students.push({ id: uid(), ...d }); db.save(); draw(); toast('Saqlandi'); } });
    const draw = () => {
      const S = db.s.students, groups = [...new Set(S.map((x) => x.group))].sort(); if (g !== 'all' && !groups.includes(g)) g = 'all';
      const avgs = S.map(studentAvg).filter((x) => x !== null); const avg = avgs.length ? Math.round(avgs.reduce((a, b) => a + b, 0) / avgs.length) : 0;
      $('.stats', root).innerHTML = stat('users', S.length, 'talabalar', 'blue') + stat('list', groups.length, 'guruhlar', 'purple') + stat('trend', avg + '%', "o'rtacha o'zlashtirish", 'green') + stat('warn', avgs.filter((a) => a < 56).length, 'xavf ostida (<56%)', 'red');
      $('.groups', root).innerHTML = ['all', ...groups].map((x) => `<button class="chip ${x === g ? 'on' : ''}" data-g="${esc(x)}">${x === 'all' ? 'Barcha guruhlar' : esc(x)}</button>`).join('');
      $$('[data-g]', root).forEach((b) => b.onclick = () => { g = b.dataset.g; draw(); });
      const L = S.filter((s) => (g === 'all' || s.group === g) && CE.norm(s.name + s.group + s.email).includes(CE.norm(q)));
      $('tbody', root).innerHTML = L.map((s) => { const a = studentAvg(s); return `<tr><td><div class="who"><span class="avatar">${esc(s.name.split(' ').map((x) => x[0]).slice(0, 2).join(''))}</span><button class="link" data-v="${s.id}">${esc(s.name)}</button></div></td><td><span class="chip">${esc(s.group)}</span></td><td>${esc(s.email)}</td><td>${a === null ? '—' : `<div class="mini-bar"><i style="width:${a}%" class="${a < 56 ? 'red' : a < 71 ? 'amber' : 'green'}"></i></div> ${a}% <small>(baho ${grade(a)})</small>`}</td><td class="act"><button class="icon-btn" data-e="${s.id}" aria-label="Tahrirlash">${icon('edit')}</button><button class="icon-btn" data-x="${s.id}" aria-label="O'chirish">${icon('trash')}</button></td></tr>`; }).join('') || `<tr><td colspan="5">${empty('users', 'Talaba topilmadi')}</td></tr>`;
      $$('[data-e]', root).forEach((b) => b.onclick = () => form(db.s.students.find((x) => x.id === b.dataset.e)));
      $$('[data-x]', root).forEach((b) => b.onclick = () => CE.confirmBox("Talabani o'chirasizmi? Uning baholari ham o'chadi.", () => { db.s.students = db.s.students.filter((x) => x.id !== b.dataset.x); db.s.assignments.forEach((a) => delete a.grades[b.dataset.x]); db.save(); draw(); }));
      $$('[data-v]', root).forEach((b) => b.onclick = () => { const s = db.s.students.find((x) => x.id === b.dataset.v); modal({ title: s.name, body: `<p class="hint">${esc(s.group)} · ${esc(s.email)}</p><table class="tbl compact"><thead><tr><th>Topshiriq</th><th>Ball</th><th>%</th></tr></thead><tbody>${db.s.assignments.map((a) => `<tr><td>${esc(a.title)}</td><td>${a.grades[s.id] ?? '—'} / ${a.max}</td><td>${a.grades[s.id] === undefined ? '—' : Math.round((a.grades[s.id] / a.max) * 100) + '%'}</td></tr>`).join('')}</tbody></table>` }); });
    };
    $('input', root).oninput = (e) => { q = e.target.value; draw(); }; $('[data-add]', root).onclick = () => form();
    $('[data-exp]', root).onclick = () => CE.download('talabalar.csv', csv([['F.I.Sh.', 'Guruh', 'E-pochta', "O'zlashtirish %"], ...db.s.students.map((s) => [s.name, s.group, s.email, studentAvg(s) ?? ''])]), 'text/csv');
    $('[data-imp]', root).onclick = () => { const body = mk(`<div><p class="hint">Har qatorga bitta talaba: <code>F.I.Sh.; Guruh; e-pochta</code></p><textarea rows="8" style="width:100%" placeholder="Aliyev Vali; KT-24; vali@example.com"></textarea></div>`); modal({ title: 'Talabalarni import qilish', body, actions: [{ label: 'Bekor qilish', cls: 'ghost' }, { label: 'Import', cls: 'primary', fn: () => { const L = $('textarea', body).value.split('\n').map((l) => l.split(/[;,\t]/).map((x) => x.trim())).filter((a) => a[0]); L.forEach((a) => db.s.students.push({ id: uid(), name: a[0], group: a[1] || 'Guruhsiz', email: a[2] || '' })); db.save(); draw(); toast(`${L.length} ta talaba qo'shildi`); } }] }); };
    draw();
  };

  // ---------- Topshiriqlar ----------
  V.assignments = (root) => {
    root.innerHTML = pageHead('Topshiriqlar va baholash', "Topshiriq yarating, baholang va natijalarni tahlil qiling", `<button class="btn primary" data-add>${icon('plus')}Yangi topshiriq</button>`) + '<div class="stats"></div><div class="cards a-cards"></div>';
    const form = () => CE.formModal({ title: 'Yangi topshiriq', values: { due: CE.iso(CE.addDays(7)), max: 100, topic: 'Analitik kimyo' }, fields: [{ k: 'title', label: 'Nomi', req: 1, full: 1 }, { k: 'topic', label: 'Fan/mavzu', type: 'select', options: CE.FIELDS.map((f) => f.name) }, { k: 'due', label: 'Muddat', type: 'date', req: 1 }, { k: 'max', label: 'Maksimal ball', type: 'number', min: 1, req: 1 }], onSubmit: (d) => { db.s.assignments.unshift({ id: uid(), title: d.title, topic: d.topic, due: d.due, max: +d.max, grades: {} }); db.save(); db.notify(`Yangi topshiriq: ${d.title}`, '#/assignments'); draw(); toast('Topshiriq yaratildi'); } });
    const grading = (a) => { const body = mk('<div class="tbl-w"><table class="tbl compact"><thead><tr><th>Talaba</th><th>Guruh</th><th>Ball</th><th>%</th></tr></thead><tbody></tbody></table></div>'); const sum = mk('<div class="grade-sum"></div>'); const fill = () => { const v = Object.values(a.grades); sum.innerHTML = v.length ? `Baholangan: <b>${v.length}/${db.s.students.length}</b> · O'rtacha: <b>${fmt(v.reduce((x, y) => x + y, 0) / v.length, 4)}</b> · Eng yuqori: <b>${Math.max(...v)}</b> · Eng past: <b>${Math.min(...v)}</b>` : 'Hali baholanmagan'; };
      $('tbody', body).innerHTML = db.s.students.map((s) => `<tr><td>${esc(s.name)}</td><td>${esc(s.group)}</td><td><input type="number" min="0" max="${a.max}" step="0.5" value="${a.grades[s.id] ?? ''}" data-s="${s.id}" aria-label="${esc(s.name)} bali"> / ${a.max}</td><td data-p="${s.id}">${a.grades[s.id] === undefined ? '—' : Math.round((a.grades[s.id] / a.max) * 100) + '%'}</td></tr>`).join('');
      $$('input', body).forEach((i) => i.oninput = () => { const v = i.value === '' ? undefined : Math.min(a.max, Math.max(0, +i.value)); if (v === undefined) delete a.grades[i.dataset.s]; else a.grades[i.dataset.s] = v; $(`[data-p="${i.dataset.s}"]`, body).textContent = v === undefined ? '—' : Math.round((v / a.max) * 100) + '%'; db.save(); fill(); });
      const wrap = mk('<div></div>'); wrap.append(sum, body); fill(); modal({ title: `Baholash: ${a.title}`, wide: true, body: wrap, onClose: draw, actions: [{ label: 'CSV', icon: 'download', cls: 'ghost', keep: true, fn: () => { CE.download('baholar.csv', csv([['Talaba', 'Guruh', 'Ball', 'Maks'], ...db.s.students.map((s) => [s.name, s.group, a.grades[s.id] ?? '', a.max])]), 'text/csv'); return false; } }, { label: 'Tayyor', cls: 'primary' }] }); };
    const draw = () => {
      const A = db.s.assignments; const gr = A.flatMap((a) => Object.values(a.grades).map((v) => (v / a.max) * 100)); const avg = gr.length ? Math.round(gr.reduce((x, y) => x + y, 0) / gr.length) : 0;
      $('.stats', root).innerHTML = stat('clip', A.length, 'topshiriqlar', 'blue') + stat('calendar', A.filter((a) => CE.days(a.due) >= 0).length, 'faol (muddati kelmagan)', 'amber') + stat('check', gr.length, 'qo\'yilgan baholar', 'green') + stat('trend', avg + '%', "o'rtacha natija", 'purple');
      $('.a-cards', root).innerHTML = A.map((a) => { const n = Object.keys(a.grades).length, N = db.s.students.length; return `<article class="card ac"><div class="ac-h"><b>${esc(a.title)}</b>${CE.dueBadge(a.due)}</div><small>${esc(a.topic)} · muddat ${CE.fmtDate(a.due)} · max ${a.max}</small><div class="pbar"><i style="width:${N ? (n / N) * 100 : 0}%"></i></div><small>${n}/${N} baholangan</small><div class="row-btn"><button class="btn primary sm" data-g="${a.id}">${icon('check')}Baholash</button><button class="icon-btn" data-x="${a.id}" aria-label="O'chirish">${icon('trash')}</button></div></article>`; }).join('') || empty('clip', "Topshiriqlar yo'q");
      $$('[data-g]', root).forEach((b) => b.onclick = () => grading(A.find((x) => x.id === b.dataset.g))); $$('[data-x]', root).forEach((b) => b.onclick = () => CE.confirmBox("Topshiriqni o'chirasizmi?", () => { db.s.assignments = db.s.assignments.filter((x) => x.id !== b.dataset.x); db.save(); draw(); }));
    };
    $('[data-add]', root).onclick = form; draw();
  };

  // ---------- Testlar ----------
  V.tests = (root) => {
    root.innerHTML = pageHead('Onlayn testlar', 'Fan bo\'limlari bo\'yicha testlar, natijalar tarixi va savollar banki', `<button class="btn primary" data-all>${icon('bolt')}Aralash test</button>`) + '<div class="stats"></div><div class="split wide"><section class="card panel"><div class="panel-h"><span class="ph-ic">' + icon('quiz') + '</span><h3>Test topshirish</h3></div><div class="tile-grid f"></div></section><section class="card panel hist"></section></div><section class="card panel bank"></section>';
    const draw = () => {
      const H = db.s.tests; const avg = H.length ? Math.round(H.reduce((a, t) => a + t.pct, 0) / H.length) : 0;
      $('.stats', root).innerHTML = stat('quiz', H.length, 'topshirilgan testlar', 'blue') + stat('trend', avg + '%', "o'rtacha natija", 'green') + stat('star', H.length ? Math.max(...H.map((t) => t.pct)) + '%' : '—', 'eng yaxshi natija', 'amber') + stat('list', CE.TESTS.length, 'savollar bazasi', 'purple');
      $('.tile-grid.f', root).innerHTML = CE.FIELDS.map((f) => `<button class="tile ${f.color}" data-f="${f.id}"><span class="t-ic">${icon(CE.FIELD_ICO[f.id])}</span><span class="t-tx"><b>${esc(f.name)}</b><small>${CE.TESTS.filter((q) => q.f === f.id).length} ta savol</small></span>${icon('play')}</button>`).join('');
      $$('[data-f]', root).forEach((b) => b.onclick = () => CE.quiz.start(b.dataset.f, 8));
      const h = $('.hist', root); const pts = H.slice().reverse().map((t, i) => [i + 1, t.pct]);
      h.innerHTML = `<div class="panel-h"><span class="ph-ic">${icon('trend')}</span><h3>Natijalar tarixi</h3></div>` + (H.length ? (pts.length > 1 ? CE.chart({ series: [{ d: pts, dots: true }], xl: 'Urinish №', yl: '%', ymin: 0, ymax: 100, h: 200, ariaLabel: 'Test natijalari' }) : '') + `<ul class="mini-list">${H.slice(0, 6).map((t) => `<li><b>${t.score}/${t.total} (${t.pct}%)</b><small>${CE.fmtDate(t.date)} · ${t.field === 'all' ? 'Aralash' : esc(fieldOf(t.field).name)} · baho ${grade(t.pct)}</small></li>`).join('')}</ul>` : empty('quiz', 'Hali test topshirilmagan'));
    };
    $('[data-all]', root).onclick = () => CE.quiz.start('all', 10);
    const bank = $('.bank', root);
    const drawBank = () => { bank.innerHTML = `<div class="panel-h"><span class="ph-ic">${icon('list')}</span><h3>Savollar banki</h3><button class="btn ghost sm" data-addq>${icon('plus')}Savol qo'shish</button></div><div class="accs">${CE.FIELDS.map((f) => `<details><summary><span class="t-ic ${f.color}">${icon(CE.FIELD_ICO[f.id])}</span><b>${esc(f.name)}</b><small>${CE.TESTS.filter((q) => q.f === f.id).length} ta</small></summary><ol class="qlist">${CE.TESTS.filter((q) => q.f === f.id).map((q) => `<li><b>${esc(q.q)}</b><ul>${q.o.map((o, i) => `<li class="${i === q.a ? 'ok' : ''}">${'ABCD'[i]}) ${esc(o)}</li>`).join('')}</ul></li>`).join('')}</ol></details>`).join('')}</div>`;
      $('[data-addq]', bank).onclick = () => CE.formModal({ title: "Yangi test savoli", values: { f: CE.FIELDS[0].name, a: 'A' }, fields: [{ k: 'f', label: 'Bo\'lim', type: 'select', options: CE.FIELDS.map((f) => f.name) }, { k: 'q', label: 'Savol', req: 1, full: 1 }, { k: 'o0', label: 'A variant', req: 1 }, { k: 'o1', label: 'B variant', req: 1 }, { k: 'o2', label: 'C variant', req: 1 }, { k: 'o3', label: 'D variant', req: 1 }, { k: 'a', label: "To'g'ri javob", type: 'select', options: ['A', 'B', 'C', 'D'] }, { k: 'e', label: 'Izoh', full: 1 }], onSubmit: (d) => { const q = { f: CE.FIELDS.find((x) => x.name === d.f).id, q: d.q, o: [d.o0, d.o1, d.o2, d.o3], a: 'ABCD'.indexOf(d.a), e: d.e || '' }; (db.s.qbank = db.s.qbank || []).push(q); CE.TESTS.push(q); db.save(); draw(); drawBank(); toast("Savol qo'shildi"); } }); };
    CE.bus.onView('tests', draw); draw(); drawBank();
  };

  // ---------- AI ----------
  V.ai = (root, sub, qs) => {
    root.innerHTML = pageHead('AI ilmiy yordamchi', 'Hisoblashlar, dars rejalari, maqola va dissertatsiya bo\'yicha yordam') + `<div class="split wide"><section class="card panel ai-p full"></section><section class="card panel"><div class="panel-h"><span class="ph-ic">${icon('info')}</span><h3>Nimalarni so'rash mumkin?</h3></div><ul class="how"><li><b>Eritma tayyorlash</b><small>0.1 M NaOH eritmasidan 500 ml tayyorlash uchun qancha NaOH kerak?</small></li><li><b>Molyar massa va mol</b><small>5 g NaCl necha mol? · CuSO4·5H2O molyar massasi</small></li><li><b>pH hisoblash</b><small>0.01 M CH3COOH ning pH i · 0.001 M HCl pH</small></li><li><b>Reaksiya balanslash</b><small>Fe + O2 -> Fe2O3</small></li><li><b>Suyultirish</b><small>2 M HCl dan 0.5 M li 250 ml tayyorlash uchun suyultirish</small></li><li><b>Tushunchalar</b><small>Le Shatelye prinsipi, flotatsiya, gidrometallurgiya, nodir yer elementlari…</small></li><li><b>Dars / maqola / dissertatsiya</b><small>Tegishli rejimni tanlab, mavzuni yozing</small></li></ul></section></div>`;
    const w = $('.ai-p', root); CE.W.ai(w, { full: true }); const q = new URLSearchParams(qs || '').get('q'); if (q) w._ask(q);
  };

  // ---------- Shablonlar ----------
  const docModal = (title, body, id) => {
    const el = mk(`<div class="doc-ed"><input class="doc-t" value="${esc(title)}" aria-label="Hujjat nomi"><textarea rows="18" spellcheck="false"></textarea></div>`); $('textarea', el).value = body;
    const cur = () => ({ title: $('.doc-t', el).value.trim() || 'Hujjat', body: $('textarea', el).value });
    const asDoc = () => { const d = cur(); return `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word"><head><meta charset="utf-8"><title>${esc(d.title)}</title></head><body style="font-family:Times New Roman;font-size:14pt"><h2>${esc(d.title)}</h2>${d.body.split('\n').map((l) => `<p style="margin:2pt 0">${esc(l).replace(/ {2}/g, '&nbsp;&nbsp;') || '&nbsp;'}</p>`).join('')}</body></html>`; };
    modal({ title: 'Hujjat muharriri', wide: true, body: el, actions: [{ label: 'Nusxalash', icon: 'copy', cls: 'ghost', keep: true, fn: () => { CE.copy(cur().body); return false; } }, { label: '.txt', icon: 'download', cls: 'ghost', keep: true, fn: () => { CE.download(cur().title + '.txt', cur().body); return false; } }, { label: 'Word (.doc)', icon: 'download', cls: 'ghost', keep: true, fn: () => { CE.download(cur().title + '.doc', asDoc(), 'application/msword'); return false; } }, { label: 'Chop etish', icon: 'print', cls: 'ghost', keep: true, fn: () => { CE.printHtml(`<h2>${esc(cur().title)}</h2><pre style="white-space:pre-wrap;font:inherit">${esc(cur().body)}</pre>`, cur().title); return false; } }, { label: 'Saqlash', icon: 'check', cls: 'primary', fn: () => { const d = cur(); if (id) { const x = db.s.docs.find((y) => y.id === id); Object.assign(x, d, { date: CE.iso(new Date()) }); } else db.s.docs.unshift({ id: uid(), ...d, date: CE.iso(new Date()) }); db.save(); CE.bus.emit('docs'); toast('Hujjat saqlandi'); } }] });
  };
  V.templates = (root, sub) => {
    root.innerHTML = pageHead('Shablonlar va hujjatlar', "Tayyor shablonlarni tahrirlang, Word/TXT ko'rinishida yuklab oling yoki chop eting", `<button class="btn primary" data-new>${icon('plus')}Bo'sh hujjat</button>`) + '<div class="cards t-cards"></div><section class="card panel mydocs"></section>';
    $('.t-cards', root).innerHTML = CE.TEMPLATES.map((t) => `<button class="card ecard" data-t="${t.id}"><span class="t-ic blue">${icon(t.ico)}</span><b>${esc(t.n)}</b><small>${t.body.split('\n').length} qator</small></button>`).join('');
    $$('[data-t]', root).forEach((b) => b.onclick = () => { const t = CE.TEMPLATES.find((x) => x.id === b.dataset.t); docModal(t.n, t.body); });
    $('[data-new]', root).onclick = () => docModal('Yangi hujjat', '');
    const d = $('.mydocs', root); const draw = () => { d.innerHTML = `<div class="panel-h"><span class="ph-ic">${icon('doc')}</span><h3>Mening hujjatlarim</h3></div>` + (db.s.docs.length ? `<ul class="rows">${db.s.docs.map((x) => `<li><span class="t-ic blue">${icon('doc')}</span><div class="grow"><b>${esc(x.title)}</b><small>${CE.fmtDate(x.date)} · ${x.body.length} belgi</small></div><button class="icon-btn" data-o="${x.id}" aria-label="Ochish">${icon('edit')}</button><button class="icon-btn" data-x="${x.id}" aria-label="O'chirish">${icon('trash')}</button></li>`).join('')}</ul>` : empty('doc', 'Hujjat saqlanmagan. Shablonni oching va «Saqlash» ni bosing.')); $$('[data-o]', d).forEach((b) => b.onclick = () => { const x = db.s.docs.find((y) => y.id === b.dataset.o); docModal(x.title, x.body, x.id); }); $$('[data-x]', d).forEach((b) => b.onclick = () => CE.confirmBox("Hujjatni o'chirasizmi?", () => { db.s.docs = db.s.docs.filter((y) => y.id !== b.dataset.x); db.save(); draw(); })); };
    CE.bus.onView('docs', draw); draw(); if (sub) { const t = CE.TEMPLATES.find((x) => x.id === sub); if (t) docModal(t.n, t.body); }
  };

  // ---------- Konferensiyalar ----------
  V.conferences = (root) => {
    root.innerHTML = pageHead('Konferensiyalar', 'Tezis topshirish muddatlari va ishtirok rejasi', `<button class="btn primary" data-add>${icon('plus')}Konferensiya qo'shish</button>`) + `<div class="cards c-cards"></div><section class="card panel"><div class="panel-h"><span class="ph-ic">${icon('ext')}</span><h3>Konferensiyalarni qidirish</h3></div><div class="chips">${CE.CONF_LINKS.map((l) => `<a class="chip" target="_blank" rel="noopener" href="${l.u}">${esc(l.n)} ${icon('ext')}</a>`).join('')}</div><p class="hint">«namuna» deb belgilangan yozuvlar — o'rnak. O'zingizniki bilan almashtiring yoki o'chiring.</p></section>`;
    const form = (c) => CE.formModal({ title: c ? 'Tahrirlash' : "Konferensiya qo'shish", values: c || { status: 'Rejada', date: CE.iso(CE.addDays(60)), deadline: CE.iso(CE.addDays(30)) }, fields: [{ k: 'name', label: 'Nomi', req: 1, full: 1 }, { k: 'date', label: 'O\'tkazilish sanasi', type: 'date', req: 1 }, { k: 'deadline', label: 'Tezis topshirish muddati', type: 'date' }, { k: 'place', label: 'Joy' }, { k: 'status', label: 'Holat', type: 'select', options: ['Rejada', 'Tezis tayyorlanmoqda', 'Topshirildi', 'Qabul qilindi', 'Rad etildi', 'Qatnashdim'] }, { k: 'url', label: 'Havola', type: 'url', full: 1 }], onSubmit: (d) => { if (c) Object.assign(c, d); else db.s.conferences.push({ id: uid(), ...d }); db.save(); draw(); toast('Saqlandi'); } });
    const draw = () => { $('.c-cards', root).innerHTML = db.s.conferences.slice().sort((a, b) => a.date.localeCompare(b.date)).map((c) => `<article class="card ac"><div class="ac-h"><b>${esc(c.name)}</b><span class="badge blue">${esc(c.status)}</span></div><small>${icon('calendar')} ${CE.fmtDate(c.date)} · ${icon('pin')} ${esc(c.place || '—')}</small>${c.deadline ? `<small>Tezis muddati: ${CE.fmtDate(c.deadline)} ${CE.dueBadge(c.deadline)}</small>` : ''}<div class="row-btn">${c.url ? `<a class="btn ghost sm" target="_blank" rel="noopener" href="${esc(c.url)}">${icon('ext')}Sayt</a>` : ''}<button class="btn ghost sm" data-cal="${c.id}">${icon('calendar')}Taqvimga</button><button class="icon-btn" data-e="${c.id}" aria-label="Tahrirlash">${icon('edit')}</button><button class="icon-btn" data-x="${c.id}" aria-label="O'chirish">${icon('trash')}</button></div></article>`).join('') || empty('slides', "Konferensiyalar yo'q");
      $$('[data-e]', root).forEach((b) => b.onclick = () => form(db.s.conferences.find((x) => x.id === b.dataset.e))); $$('[data-x]', root).forEach((b) => b.onclick = () => CE.confirmBox("O'chirasizmi?", () => { db.s.conferences = db.s.conferences.filter((x) => x.id !== b.dataset.x); db.save(); draw(); }));
      $$('[data-cal]', root).forEach((b) => b.onclick = () => { const c = db.s.conferences.find((x) => x.id === b.dataset.cal); db.s.events.push({ id: uid(), date: c.date, time: '09:00', title: `Konferensiya: ${c.name}`, color: 'green' }); if (c.deadline) db.s.events.push({ id: uid(), date: c.deadline, time: '12:00', title: `Tezis muddati: ${c.name}`, color: 'red' }); db.save(); toast('Taqvimga qo\'shildi'); }); };
    $('[data-add]', root).onclick = () => form(); draw();
  };

  // ---------- Taqvim ----------
  V.calendar = (root) => {
    db.s.todos = db.s.todos || [{ id: uid(), t: "Talabalar uchun test savollarini tayyorlash", done: false }, { id: uid(), t: 'Grant hisobotining 2-bo\'limini yozish', done: false }];
    root.innerHTML = pageHead('Rejalar va taqvim', 'Tadbirlar, muddatlar va shaxsiy vazifalar') + `<div class="split wide"><section class="card panel cal-p big"></section><div class="col"><section class="card panel up"></section><section class="card panel todo"></section></div></div>`;
    CE.W.calendar($('.cal-p', root), { big: true });
    const up = $('.up', root); const drawUp = () => { const t = CE.iso(new Date()), e = CE.iso(CE.addDays(14)); const L = db.s.events.filter((x) => x.date >= t && x.date <= e).sort((a, b) => (a.date + a.time).localeCompare(b.date + b.time)); up.innerHTML = `<div class="panel-h"><span class="ph-ic">${icon('bell')}</span><h3>Yaqin 14 kun</h3></div><ul class="ev-list">${L.map((x) => `<li class="${x.color}"><time>${CE.fmtDate(x.date)}<br>${esc(x.time)}</time><span>${esc(x.title)}</span></li>`).join('') || '<li class="empty-s">Tadbirlar yo\'q</li>'}</ul>`; }; CE.bus.onView('events', drawUp); drawUp();
    const td = $('.todo', root); const drawT = () => { td.innerHTML = `<div class="panel-h"><span class="ph-ic">${icon('check')}</span><h3>Vazifalar</h3></div><div class="chk-list">${db.s.todos.map((x) => `<label class="chk"><input type="checkbox" data-i="${x.id}" ${x.done ? 'checked' : ''}><span class="${x.done ? 'done' : ''}">${esc(x.t)}</span><button type="button" class="icon-btn sm" data-d="${x.id}" aria-label="O'chirish">${icon('x')}</button></label>`).join('') || '<p class="empty-s">Vazifalar yo\'q</p>'}</div><form class="inline-form add"><input name="t" placeholder="Yangi vazifa…"><button class="btn ghost" type="submit">${icon('plus')}</button></form>`;
      $$('[data-i]', td).forEach((c) => c.onchange = () => { db.s.todos.find((x) => x.id === c.dataset.i).done = c.checked; db.save(); drawT(); }); $$('[data-d]', td).forEach((b) => b.onclick = (e) => { e.preventDefault(); db.s.todos = db.s.todos.filter((x) => x.id !== b.dataset.d); db.save(); drawT(); });
      $('form', td).onsubmit = (e) => { e.preventDefault(); const v = e.target.t.value.trim(); if (!v) return; db.s.todos.push({ id: uid(), t: v, done: false }); db.save(); drawT(); }; }; drawT();
  };

  // ---------- Loyiha va grantlar ----------
  V.projects = (root) => {
    let f = 'all';
    root.innerHTML = pageHead('Loyiha va grantlar', 'Loyihalar, grantlar, byudjet va muddatlar', `<button class="btn primary" data-add>${icon('plus')}Yangi loyiha</button>`) + `<div class="stats"></div><div class="toolbar"><div class="chips pick fl"></div></div><div class="cards p-cards"></div><section class="card panel"><div class="panel-h"><span class="ph-ic">${icon('coin')}</span><h3>Grant imkoniyatlari (resurslar)</h3></div><div class="chips">${[['Erasmus+', 'https://erasmus-plus.ec.europa.eu/'], ['Horizon Europe', 'https://research-and-innovation.ec.europa.eu/funding/funding-opportunities/funding-programmes-and-open-calls/horizon-europe_en'], ['DAAD', 'https://www.daad.de/en/'], ['UNESCO fellowships', 'https://www.unesco.org/en/fellowships'], ['Grants.gov', 'https://www.grants.gov/']].map(([n, u]) => `<a class="chip" target="_blank" rel="noopener" href="${u}">${n} ${icon('ext')}</a>`).join('')}</div></section>`;
    const form = (p) => CE.formModal({ title: p ? 'Loyihani tahrirlash' : 'Yangi loyiha', values: p || { type: 'Loyiha', status: 'Rejalashtirilgan', progress: 0, budget: 0, deadline: CE.iso(CE.addDays(90)) }, fields: [{ k: 'title', label: 'Nomi', req: 1, full: 1 }, { k: 'type', label: 'Turi', type: 'select', options: ['Loyiha', 'Grant', 'Maqola', 'Patent'] }, { k: 'status', label: 'Holat', type: 'select', options: ['Rejalashtirilgan', 'Jarayonda', 'Yozilmoqda', 'Topshirilgan', 'Yakunlangan'] }, { k: 'budget', label: "Byudjet (mln so'm)", type: 'number', min: 0, step: 'any' }, { k: 'deadline', label: 'Muddat', type: 'date' }, { k: 'progress', label: 'Jarayon, %', type: 'number', min: 0, max: 100 }, { k: 'desc', label: 'Tavsif', type: 'textarea', full: 1 }], onSubmit: (d) => { d.budget = +d.budget || 0; d.progress = Math.min(100, Math.max(0, +d.progress || 0)); if (p) Object.assign(p, d); else db.s.projects.unshift({ id: uid(), ...d }); db.save(); CE.bus.emit('projects'); draw(); toast('Saqlandi'); } });
    const draw = () => {
      const P = db.s.projects; const types = ['all', ...new Set(P.map((p) => p.type))]; if (!types.includes(f)) f = 'all';
      $('.stats', root).innerHTML = stat('brief', P.length, 'jami loyihalar', 'blue') + stat('bolt', P.filter((p) => p.status === 'Jarayonda' || p.status === 'Yozilmoqda').length, 'jarayonda', 'amber') + stat('coin', fmt(P.reduce((a, p) => a + p.budget, 0), 5), "umumiy byudjet, mln so'm", 'green') + stat('trend', P.length ? Math.round(P.reduce((a, p) => a + p.progress, 0) / P.length) + '%' : '0%', "o'rtacha jarayon", 'purple');
      $('.fl', root).innerHTML = types.map((t) => `<button class="chip ${t === f ? 'on' : ''}" data-f="${esc(t)}">${t === 'all' ? 'Barchasi' : esc(t)}</button>`).join(''); $$('[data-f]', root).forEach((b) => b.onclick = () => { f = b.dataset.f; draw(); });
      $('.p-cards', root).innerHTML = P.filter((p) => f === 'all' || p.type === f).map((p) => `<article class="card ac"><div class="ac-h"><b>${esc(p.title)}</b><span class="badge blue">${esc(p.type)}</span></div><small>${esc(p.desc || '')}</small><div class="pbar"><i style="width:${p.progress}%"></i></div><input type="range" min="0" max="100" value="${p.progress}" data-r="${p.id}" aria-label="Jarayon"><small>${esc(p.status)} · ${p.progress}% · ${p.budget ? p.budget + " mln so'm · " : ''}${p.deadline ? 'muddat ' + CE.fmtDate(p.deadline) + ' ' : ''}${p.deadline ? CE.dueBadge(p.deadline) : ''}</small><div class="row-btn"><button class="icon-btn" data-e="${p.id}" aria-label="Tahrirlash">${icon('edit')}</button><button class="icon-btn" data-x="${p.id}" aria-label="O'chirish">${icon('trash')}</button></div></article>`).join('') || empty('brief', 'Loyihalar yo\'q');
      $$('[data-r]', root).forEach((r) => r.onchange = () => { db.s.projects.find((x) => x.id === r.dataset.r).progress = +r.value; db.save(); draw(); }); $$('[data-e]', root).forEach((b) => b.onclick = () => form(db.s.projects.find((x) => x.id === b.dataset.e))); $$('[data-x]', root).forEach((b) => b.onclick = () => CE.confirmBox("Loyihani o'chirasizmi?", () => { db.s.projects = db.s.projects.filter((x) => x.id !== b.dataset.x); db.save(); CE.bus.emit('projects'); draw(); }));
    };
    $('[data-add]', root).onclick = () => form(); draw();
  };

  // ---------- Sozlamalar ----------
  V.settings = (root) => {
    const p = db.s.profile;
    root.innerHTML = pageHead('Sozlamalar', 'Profil, ko\'rinish va ma\'lumotlarni boshqarish') + `<div class="split wide"><section class="card panel"><div class="panel-h"><span class="ph-ic">${icon('user')}</span><h3>Profil</h3></div><form class="form-grid prof-f"><label class="full"><span>F.I.Sh.</span><input name="name" value="${esc(p.name)}" required></label><label class="full"><span>Lavozim</span><input name="role" value="${esc(p.role)}"></label><label class="full"><span>Tashkilot</span><input name="org" value="${esc(p.org)}"></label><button class="btn primary" type="submit">Saqlash</button></form><div class="panel-h" style="margin-top:22px"><span class="ph-ic">${icon('sun')}</span><h3>Ko'rinish</h3></div><div class="chips pick th">${[['light', "Yorug'"], ['dark', "Qorong'i"], ['auto', 'Avtomatik']].map(([k, l]) => `<button class="chip ${db.s.theme === k ? 'on' : ''}" data-t="${k}">${l}</button>`).join('')}</div></section><div class="col"><section class="card panel"><div class="panel-h"><span class="ph-ic">${icon('download')}</span><h3>Ma'lumotlar</h3></div><p class="hint">Barcha ma'lumotlar faqat shu brauzerda (localStorage) saqlanadi. Zaxira nusxa olib turing.</p><div class="row-btn"><button class="btn ghost" data-exp>${icon('download')}Eksport (JSON)</button><label class="btn ghost file">${icon('plus')}Import<input type="file" accept="application/json" hidden></label></div><div class="row-btn"><button class="btn ghost" data-demo>${icon('refresh')}Demo ma'lumotlarni tiklash</button><button class="btn danger" data-clear>${icon('trash')}Hammasini tozalash</button></div></section><section class="card panel"><div class="panel-h"><span class="ph-ic">${icon('gear')}</span><h3>Tezkor tugmalar</h3></div><ul class="kbd"><li><kbd>/</kbd> Qidiruvga o'tish</li><li><kbd>Esc</kbd> Oynani yopish</li><li><kbd>←</kbd><kbd>→</kbd> Taqdimotda slaydlar</li><li><kbd>F</kbd> Taqdimotda to'liq ekran</li></ul></section></div></div>`;
    $('.prof-f', root).onsubmit = (e) => { e.preventDefault(); Object.assign(db.s.profile, Object.fromEntries(new FormData(e.target))); db.save(); CE.bus.emit('profile'); toast('Profil yangilandi'); };
    $$('[data-t]', root).forEach((b) => b.onclick = () => { db.s.theme = b.dataset.t; db.save(); CE.applyTheme(); $$('[data-t]', root).forEach((x) => x.classList.toggle('on', x === b)); });
    $('[data-exp]', root).onclick = () => CE.download(`chemedu_zaxira_${CE.iso(new Date())}.json`, JSON.stringify(db.s, null, 2), 'application/json');
    $('input[type=file]', root).onchange = (e) => { const f = e.target.files[0]; if (!f) return; const r = new FileReader(); r.onload = () => { try { const d = JSON.parse(r.result); if (d.v !== 1 || !d.profile) throw new Error(); db.s = d; localStorage.setItem('chemedu.v1', JSON.stringify(d)); location.reload(); } catch (err) { toast("Fayl formati noto'g'ri", 'err'); } }; r.readAsText(f); };
    $('[data-demo]', root).onclick = () => CE.confirmBox("Barcha o'zgarishlar o'chib, demo ma'lumotlar tiklanadi. Davom etasizmi?", () => { db.reset(); setTimeout(() => location.reload(), 150); });
    $('[data-clear]', root).onclick = () => CE.confirmBox("Barcha ma'lumotlar (talabalar, maqolalar, jurnal va h.k.) o'chiriladi!", () => { db.reset(); const s = db.s; Object.assign(s, { lessons: [], projects: [], articles: [], students: [], assignments: [], events: [], activity: [], journal: [], conferences: [], notifications: [], tests: [], docs: [], chat: {}, todos: [] }); s.thesis.groups.forEach((g) => g.items = []); s.thesis.chapters = []; db.save(); setTimeout(() => location.reload(), 150); });
  };
})();
